---
- include_tasks:        'tasks/common/install_packages.yml'
#- include_tasks:        'tasks/common/lines_in_files.yml'
- include_tasks:        'tasks/common/enable_services.yml'
  when:                 install_packages_result.changed
- include_tasks:        'tasks/common/start_services.yml'
  when:                 install_packages_result.changed
#- include_tasks:        'tasks/common/restart_services.yml'
#  when:                 lines_in_files_result.changed
